export const objections = {
  'doesnt-scale': {
    title: '"That works in relationships, but not in a society of millions."',
    subtitle: 'Persuasion requires trust. Strangers don\'t have it.',
    steelman: 'Personal relationships involve people who know and care about each other. Society involves millions of strangers with competing interests. Persuasion works with your spouse because you share a life. It doesn\'t work with strangers because there\'s no relationship to preserve. Large-scale cooperation requires rules, and rules require enforcement. That\'s not a flaw in the system — it\'s the only way complex societies can function.',
    response: [
      'Look at the reasons you gave for rejecting force in your own life. Most of them weren\'t about the relationship. They were about what force <em>does to human beings</em>: it breeds resentment, it doesn\'t change beliefs, the long-term costs outweigh the short-term gains. Those effects don\'t require intimacy. They\'re features of human nature. A stranger forced to comply is just as resentful and just as unchanged in their beliefs as someone you love.',
      'The flourishing conditions you identified from your own life — safety, autonomy, connection, opportunity — don\'t have a scale threshold. A policy that violates someone\'s autonomy doesn\'t become less damaging to their flourishing because it was enacted by a large legislature rather than imposed by a single bully. The effect on the person being forced is the same.',
      'Cooperation itself is what scales. Language scaled from small groups to global communication. Markets scaled from village barter to worldwide commerce. Standards of behavior scaled from tribal custom to international norms. Every one of these was a technology of voluntary coordination that people said couldn\'t work beyond a small group — until it did.',
      'The real scaling problem runs in the other direction. Force scales <em>badly</em>. The larger the group, the less the enforcers know about the people they\'re coercing, the less feedback they receive, and the more damage they do per mistake. A parent who forces a child to eat vegetables may be wrong, but the harm is contained. A government forcing a nutrition policy on millions produces cascading unintended consequences — because the people making the rules are strangers to the people living under them.'
    ],
    concession: 'Voluntary cooperation at scale requires something coercion doesn\'t: trust between strangers. Building that trust is genuinely harder than passing a law. The philosophy doesn\'t claim the transition is simple. It claims that the alternative — forcing strangers to comply with rules they didn\'t choose — produces the very mistrust that makes cooperation seem impossible. Trust is built by cooperating. It is eroded by coercing.',
    question: 'You wouldn\'t use force on someone you know because you understand what it does to them. What makes you confident it does something different to someone you don\'t know?'
  },

  'too-urgent': {
    title: '"People are suffering right now. They can\'t wait for voluntary action."',
    subtitle: 'Urgency demands guaranteed response, not hopeful cooperation.',
    steelman: 'A child is hungry right now. A person is dying of a treatable disease right now. A family lost their home right now. You can philosophize about voluntary cooperation, but these people can\'t wait for someone to be persuaded to help. Compulsory systems exist because urgent suffering demands guaranteed, immediate response. Leaving it to voluntary action means accepting that some people will simply not be helped.',
    response: [
      'This objection carries real moral weight, and the philosophy takes it seriously. But notice the assumption underneath it: that the only way to guarantee help is to force people to provide it. This assumes that human beings, left free, will not respond to suffering. That assumption is worth testing.',
      'When disaster strikes — hurricanes, earthquakes, floods — voluntary response is not slow. It is often faster and more effective than government mobilization. After Hurricane Katrina, volunteers in their own boats reached stranded families in the first days, often before official crews did. After earthquakes, neighbors pull each other from rubble before emergency services arrive. The impulse to help is not something governments created. It is something human beings do.',
      'Now apply the flourishing framework you just worked through. When help is compelled — extracted from some to be given to others through force — what happens to the people on both ends? The person taxed loses autonomy over their resources. The person helped receives aid delivered by a system that has no relationship with them and no incentive to care about their dignity. Contrast this with voluntary help: a community that <em>chooses</em> to support its members creates connection, preserves dignity, and strengthens the social bonds that prevent future crises. Compelled help can address the symptom. Voluntary help can address the symptom <em>and</em> build the conditions for flourishing.',
      'There is a quieter cost too. When care becomes something the government does, it becomes easier for the rest of us to stop doing it. Mutual aid societies, lodges, and church relief funds once carried much of this work, and many faded as public programs grew. When a compulsory system misses someone, and every system misses someone, the person who falls needs a community that still knows how to catch them.'
    ],
    concession: 'This is where the philosophy must be most honest. During any transition from compulsory to voluntary systems, there is a real risk that some people who currently receive help would experience disruption. The philosophy cannot promise zero casualties. What it can say is this: compulsory systems produce their own suffering — dependency, loss of dignity, bureaucratic indifference, the erosion of community bonds. A system that guarantees a floor may also enforce a ceiling. The question is not whether voluntary systems are perfect. It\'s whether they produce better trajectories for human flourishing than systems built on force.',
    question: 'If you saw a neighbor in crisis, would you help — or would you wait for a government program? If you would help, why do you assume other people wouldn\'t?'
  },

  'force-built-this': {
    title: '"Force built the stability that made your flourishing possible."',
    subtitle: 'You\'re flourishing because of government, not in spite of it.',
    steelman: 'The best period of your life didn\'t happen in a vacuum. It happened inside a society with enforceable laws, public infrastructure, courts, police, and institutions — all funded and maintained through compulsory taxation. The safety, autonomy, and opportunity you identified weren\'t gifts of nature. They were products of a system built on democratic force. You\'re flourishing because of coercive institutions, not in spite of them.',
    response: [
      'This is a serious argument, and it deserves a careful answer. Start with a distinction the philosophy draws. Courts and police that stop violence, theft, and fraud are defending people against force. The principle is aimed at the <em>initiation</em> of force: taking people\'s property, time, or freedom to advance someone\'s values or solve someone\'s problem. Much of the stability you credit is the first kind. The philosophy does not claim that every outcome of the second kind is bad either. It claims the method always costs something, even when the outcome looks good.',
      'Consider the flourishing conditions you identified: safety, autonomy, connection, competence, purpose, opportunity. Now ask: did coercive institutions <em>create</em> these, or did they emerge in spite of coercion? Safety exists in your neighborhood primarily because your neighbors choose not to harm each other — not because police are on every corner. Your autonomy exists because you\'ve carved out a life within a system that limits your autonomy in dozens of ways you\'ve learned to navigate around. The stability you experience comes largely from the voluntary cooperation of millions of people — showing up to work, honoring agreements, treating strangers with basic decency — with government enforcement filling gaps where voluntary norms have broken down.',
      'The philosophy makes a distinction worth sitting with: the trust that makes cooperation possible is built by voluntary behavior, not by enforcement. A neighborhood where people don\'t steal because they respect each other is fundamentally different from one where people don\'t steal because they fear punishment. The first produces genuine trust. The second produces compliance that evaporates the moment enforcement weakens.',
      'There is also a visibility problem in this argument. You can see the road the taxes built. You can\'t see what the same money and hours would have built in the hands of the people they were taken from: the business never started, the housing a zoning rule blocked, the project never attempted because compliance cost too much. The benefits of force are easy to credit because they are visible. The costs are easy to ignore because they are not.'
    ],
    concession: 'Some compulsory institutions have produced things that voluntary ones haven\'t yet matched at the same scale. The philosophy has to say that plainly, and it cannot prove what the alternative would have built. What it claims is narrower and harder to escape: whatever force bought, it bought by taking from people who did not agree, and that taking always subtracted from their happiness, harmony, and prosperity. A good result does not erase the cost. It hides it.',
    question: 'Think about your best period again. How much of what made it good was provided by the government — and how much was built by you and the people around you, through voluntary effort, voluntary relationships, and voluntary commitment?'
  },

  'power-vacuum': {
    title: '"Without enforcement, the powerful will exploit the weak."',
    subtitle: 'Remove government force and worse force fills the vacuum.',
    steelman: 'History is clear: when centralized authority weakens, the powerful fill the vacuum. Warlords, monopolists, slaveholders, feudal lords. Government force isn\'t perfect, but it\'s the best tool humanity has developed for protecting ordinary people from predatory power. Remove it, and the vulnerable suffer most. Your philosophy sounds like freedom for the strong and abandonment of the weak.',
    response: [
      'Start with what the philosophy does not say. It does not say the weak should go undefended. Its moral principle is a commitment not to <em>initiate</em> violence or take anyone\'s property or time by force or fraud. Stopping a predator is not initiating anything. So the real question is narrower than it first appears: not whether anyone should protect the vulnerable from exploitation, but whether the institution doing the protecting should also be permitted to initiate force for everything else.',
      'That second permission is where the danger comes back in. Power to take property and compel behavior is valuable, so the strong compete to control it. Regulators are often captured by the industries they oversee. Tax codes fill with exemptions written for people who can afford lobbyists. Licensing rules keep newcomers out of trades. The institution you are counting on to protect the weak is also the prize the strong have the most reason to win.',
      'Now consider what <em>actually</em> protects the vulnerable in your own life. When someone in your community is in trouble, what helps them? Government programs, sometimes. But more often: neighbors, friends, family, religious communities, mutual aid networks, charitable organizations. These are voluntary institutions built on trust and connection — and they serve the vulnerable precisely because no one is forced to participate. The people who show up are the people who care. The help they provide preserves dignity because it comes from genuine concern, not bureaucratic obligation.',
      'The philosophy\'s claim is not that the vulnerable don\'t need protection. It\'s that the more an institution is allowed to initiate force, the more it is worth capturing, and the more it will be used against the very people it was built to protect. Defense against violence is one thing. A standing license to coerce is another. The first protects the weak. The second eventually gets aimed at them.'
    ],
    concession: 'This is the hardest question the philosophy faces. Where defense against violence is weak, people with power exploit others, and the philosophy doesn\'t deny it. Drawing a clean line between defending people and coercing them is hard in practice, and reasonable people will argue about where it falls. Voluntary protection also depends on strong communities and high trust, which take time to build. If coercive programs were withdrawn faster than those were built, some people would be more exposed than they are today. That cost is real, and an honest philosophy has to name it.',
    question: 'The institution you trust to protect the vulnerable has the power to imprison, seize property, and deploy armed agents. Who protects the vulnerable from <em>it</em>?'
  }
}
