export const objections = {
  'doesnt-scale': {
    title: '"That works in relationships, but not in a society of millions."',
    subtitle: 'Persuasion requires trust. Strangers don\'t have it.',
    steelman: 'Personal relationships involve people who know and care about each other. Society involves millions of strangers with competing interests. Persuasion works with your spouse because you share a life. It doesn\'t work with strangers because there\'s no relationship to preserve. Large-scale cooperation requires rules, and rules require enforcement. That\'s not a flaw in the system — it\'s the only way complex societies can function.',
    response: [
      'Look at the reasons you gave for rejecting force in your own life. Most of them weren\'t about the relationship. They were about what force <em>does to human beings</em>: it breeds resentment, it doesn\'t change beliefs, the long-term costs outweigh the short-term gains. None of that requires intimacy, and none of it has a scale threshold. A stranger forced to comply is just as resentful and just as unchanged as someone you love, and a policy that overrides them does not become less damaging because a legislature enacted it rather than a single bully. The effect on the person being forced is the same.',
      'Strangers already cooperate without trust. Reputation, contracts, repeat dealing, warranties, and the plain cost of losing a customer make honesty pay between people who will never meet. And the rules that coordinate millions are mostly voluntary: language, merchant custom, technical standards, private arbitration. Markets grew from village barter to worldwide commerce, and language from small groups to global communication. Each was said to be impossible beyond a small group — until it wasn\'t. None of it needed an enforcer.',
      'The real scaling problem runs in the other direction. Force scales <em>badly</em>. The larger the group, the less the enforcers know about the people they\'re coercing, the less feedback they receive, and the more damage they do per mistake. A parent who forces a child to eat vegetables may be wrong, but the harm is contained. A government forcing a nutrition policy on millions produces cascading unintended consequences — because the people making the rules are strangers to the people living under them.'
    ],
    concessionLabel: 'What takes time',
    concession: 'What takes time is not trust between strangers. Strangers already deal with each other through reputation, contracts, and competition, none of which requires trusting anyone first. What takes time is rebuilding the habits and institutions that compulsory systems crowded out. Forcing strangers to comply with rules they didn\'t choose produces the very mistrust that makes cooperation seem impossible. Trust is built by cooperating. It is eroded by coercing.',
    question: 'You wouldn\'t use force on someone you know because you understand what it does to them. What makes you confident it does something different to someone you don\'t know?'
  },

  'too-urgent': {
    title: '"People are suffering right now. They can\'t wait for voluntary action."',
    subtitle: 'Urgency demands guaranteed response, not hopeful cooperation.',
    steelman: 'A child is hungry right now. A person is dying of a treatable disease right now. A family lost their home right now. You can philosophize about voluntary cooperation, but these people can\'t wait for someone to be persuaded to help. Compulsory systems exist because urgent suffering demands guaranteed, immediate response. Leaving it to voluntary action means accepting that some people will simply not be helped.',
    response: [
      'The objection rests on an assumption: that compulsory help is guaranteed and immediate. It is neither. Funding lapses. Eligibility rules exclude. Delay is the norm, because a distant administrator cannot see who needs what tonight, and the people who can see it are waiting for authorization.',
      'When disaster strikes — hurricanes, earthquakes, floods — voluntary response is not slow. It is often faster than government mobilization. After Hurricane Katrina, volunteers in their own boats reached stranded families in the first days, and private supply trucks were unloading before the official response was organized. After earthquakes, neighbors pull each other from rubble before emergency services arrive. The impulse to help is not something governments created. It is something human beings do.',
      'When help is compelled — extracted from some to be given to others through force — look at both ends. The person taxed loses control of their resources. The person helped receives aid from a system that has no relationship with them and no incentive to care about their dignity. Compelled help addresses the symptom. Voluntary help — a community that <em>chooses</em> to support its members — addresses the symptom <em>and</em> builds the connection, dignity, and bonds that prevent the next crisis.',
      'There is a quieter cost too. When care becomes something the government does, it becomes easier for the rest of us to stop doing it. Mutual aid societies, lodges, and church relief funds once carried much of this work, and many faded as public programs grew. When a compulsory system misses someone, and every system misses someone, the person who falls needs a community that still knows how to catch them.'
    ],
    concessionLabel: 'What takes time',
    concession: 'Compulsory systems produce their own suffering — dependency, loss of dignity, bureaucratic indifference, the erosion of community bonds. A system that guarantees a floor may also enforce a ceiling. What takes time is rebuilding the mutual aid those systems displaced, and during that rebuilding some people would feel the change. But the comparison is never voluntary risk against a compulsory guarantee. It is casualties against casualties: the waitlist, the eligibility cliff, the help that arrives late or never — and those casualties are here now.',
    question: 'If you saw a neighbor in crisis, would you help — or would you wait for a government program? If you would help, why do you assume other people wouldn\'t?'
  },

  'force-built-this': {
    title: '"Force built the stability that made your flourishing possible."',
    subtitle: 'You\'re flourishing because of government, not in spite of it.',
    steelman: 'The best period of your life didn\'t happen in a vacuum. It happened inside a society with enforceable laws, public infrastructure, courts, police, and institutions — all funded and maintained through compulsory taxation. The safety, autonomy, and opportunity you identified weren\'t gifts of nature. They were products of a system built on democratic force. You\'re flourishing because of coercive institutions, not in spite of them.',
    response: [
      'Start with a distinction the philosophy draws. Courts and police that stop violence, theft, and fraud are defending people against force. The principle is aimed at the <em>initiation</em> of force: taking people\'s property, time, or freedom to advance someone\'s values or solve someone\'s problem. Much of the stability you credit is the first kind. Where it is the second kind, the outcome looks good only because its costs are hidden — paid by other people, at another time, off the books.',
      'Consider the flourishing conditions you identified: safety, autonomy, connection, competence, purpose, opportunity. Now ask: did coercive institutions <em>create</em> these, or did they emerge in spite of coercion? Safety exists in your neighborhood primarily because your neighbors choose not to harm each other — not because police are on every corner. The stability you experience comes largely from the voluntary cooperation of millions of people — showing up to work, honoring agreements, treating strangers with basic decency — with government enforcement filling gaps where voluntary norms have broken down.',
      'The trust that makes cooperation possible is built by voluntary behavior, not by enforcement. A neighborhood where people don\'t steal because they respect each other is fundamentally different from one where people don\'t steal because they fear punishment. The first produces genuine trust. The second produces compliance that evaporates the moment enforcement weakens.',
      'There is also a visibility problem in this argument. You can see the road the taxes built. You can\'t see what the same money and hours would have built in the hands of the people they were taken from: the business never started, the housing a zoning rule blocked, the project never attempted because compliance cost too much. The benefits of force are easy to credit because they are visible. The costs are easy to ignore because they are not.'
    ],
    concessionLabel: 'The hidden cost',
    concession: 'The comparison is rigged. Voluntary versions were taxed to fund their compulsory rivals, crowded out by them, or banned: the American Letter Mail Company undercut the Post Office until Congress legislated it out of existence. Their absence is evidence of crowding out, not impossibility. And whatever force bought, it bought by taking from people who did not agree, and that taking always subtracted from their happiness, harmony, and prosperity. A good result does not erase the cost. It hides it.',
    question: 'Think about your best period again. How much of what made it good was provided by the government — and how much was built by you and the people around you, through voluntary effort, voluntary relationships, and voluntary commitment?'
  },

  'power-vacuum': {
    title: '"Without enforcement, the powerful will exploit the weak."',
    subtitle: 'Remove government force and worse force fills the vacuum.',
    steelman: 'History is clear: when centralized authority weakens, the powerful fill the vacuum. Warlords, monopolists, slaveholders, feudal lords. Government force isn\'t perfect, but it\'s the best tool humanity has developed for protecting ordinary people from predatory power. Remove it, and the vulnerable suffer most. Your philosophy sounds like freedom for the strong and abandonment of the weak.',
    response: [
      'Start with what the philosophy does not say. It does not say the weak should go undefended. Its moral principle is a commitment not to <em>initiate</em> violence or take anyone\'s property or time by force or fraud. Stopping a predator is not initiating anything. So the real question is narrower than it first appears: not whether anyone should protect the vulnerable from exploitation, but whether the institution doing the protecting should also be permitted to initiate force for everything else.',
      'That second permission is where the danger comes back in. Power to take property and compel behavior is valuable, so the strong compete to control it. Regulators are often captured by the industries they oversee. Tax codes fill with exemptions written for people who can afford lobbyists. Licensing rules keep newcomers out of trades. The institution you are counting on to protect the weak is also the prize the strong have the most reason to win.',
      'Now consider what <em>actually</em> protects the vulnerable in your own life. When someone in your community is in trouble, what helps them? Government programs, sometimes. But more often: neighbors, friends, family, religious communities, mutual aid networks, charitable organizations. These are voluntary institutions built on trust and connection — and they serve the vulnerable precisely because no one is forced to participate. The people who show up are the people who care. The help they provide preserves dignity because it comes from genuine concern, not bureaucratic obligation.',
      'The objection\'s own examples make the point. Slavery was enforced by law. Feudal lords and warlords were the governments of their day. Lasting monopolies rest on state-granted privilege. Defense against violence is one thing. A standing license to coerce is another. The first protects the weak. The second eventually gets aimed at them.'
    ],
    concessionLabel: 'The line',
    concession: 'The line between defending someone and initiating force against them is not blurry. It is the line the principle rests on. Courts have held that police owe no duty to protect any particular person, so the weak are already on their own more often than the objection admits. The largest predator in history is the state itself. Private security, insurance, and arbitration already protect people every day without a license to initiate force against anyone. Protection needs a defender. It does not need a monopoly.',
    question: 'The institution you trust to protect the vulnerable has the power to imprison, seize property, and deploy armed agents. Who protects the vulnerable from <em>it</em>?'
  }
}
