import { pageMeta, SITE_URL, SITE_NAME } from '@/utils/seo'

/**
 * Applies server-rendered SEO + Open Graph tags for a page.
 * `key` indexes into app/utils/seo.js; pass overrides for dynamic pages.
 */
export function usePageSeo(key, overrides = {}) {
  const route = useRoute()
  const meta = { ...(pageMeta[key] || pageMeta.home), ...overrides }

  const fullTitle = key === 'home' ? meta.title : `${meta.title} — ${SITE_NAME}`
  const url = `${SITE_URL}${route.path}`
  // One card per page, generated by scripts/generate-og.mjs and committed.
  // A shared link carrying its own question reads as an argument someone is
  // making; the identical branded card every page used to share reads as
  // marketing, which is fatal when the recipient already disagrees with you.
  const image = meta.image || `${SITE_URL}/og/${key}.png`

  useSeoMeta({
    title: fullTitle,
    description: meta.description,
    ogType: 'website',
    ogSiteName: SITE_NAME,
    ogLocale: 'en_US',
    ogTitle: meta.title,
    ogDescription: meta.description,
    ogUrl: url,
    ogImage: image,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageAlt: meta.title,
    twitterCard: 'summary_large_image',
    twitterTitle: meta.title,
    twitterDescription: meta.description,
    twitterImage: image,
    twitterImageAlt: meta.title
  })

  useHead({ link: [{ rel: 'canonical', href: url }] })

  // Structured data. Without this Google has no machine-readable statement of
  // what this site is or who publishes it — it has to infer everything from
  // prose, and the phrase "Human Respect" barely appears in the body copy.
  const graph =
    key === 'home'
      ? [
          {
            '@type': 'WebSite',
            '@id': `${SITE_URL}/#website`,
            url: SITE_URL,
            name: SITE_NAME,
            description: meta.description,
            publisher: { '@id': `${SITE_URL}/#organization` },
            inLanguage: 'en-US'
          },
          {
            '@type': 'Organization',
            '@id': `${SITE_URL}/#organization`,
            name: SITE_NAME,
            url: SITE_URL,
            logo: `${SITE_URL}/hr-monogram-512.png`,
            description:
              'The Philosophy of Human Respect — an interactive exploration of how ' +
              'voluntary cooperation relates to human flourishing.'
          }
        ]
      : [
          {
            '@type': 'Article',
            '@id': `${url}#article`,
            headline: meta.title,
            description: meta.description,
            url,
            isPartOf: { '@id': `${SITE_URL}/#website` },
            publisher: { '@id': `${SITE_URL}/#organization` },
            inLanguage: 'en-US'
          }
        ]

  useHead({
    script: [
      {
        type: 'application/ld+json',
        innerHTML: JSON.stringify({ '@context': 'https://schema.org', '@graph': graph })
      }
    ]
  })
}
