export const objections = {
  'doesnt-scale': {
    title: '"That works in relationships, but not in a society of millions."',
    subtitle: 'Persuasion requires trust. Strangers don\'t have it.',
    steelman: 'Personal relationships involve people who know and care about each other. Society involves millions of strangers with competing interests. Persuasion works with your spouse because you share a life. It doesn\'t work with strangers because there\'s no relationship to preserve. Large-scale cooperation requires rules, and rules require enforcement. That\'s not a flaw in the system — it\'s the only way complex societies can function.',
    response: [
      'Look at the reasons you gave for rejecting force in your own life. Most of them weren\'t about the relationship. They were about what force <em>does to human beings</em>: it breeds resentment, it doesn\'t change beliefs, the long-term costs outweigh the short-term gains. Those effects don\'t require intimacy. They\'re features of human nature. A stranger forced to comply is just as resentful and just as unchanged in their beliefs as someone you love.',
      'The flourishing conditions you identified from your own life — safety, autonomy, connection, opportunity — don\'t have a scale threshold. A policy that violates someone\'s autonomy doesn\'t become less damaging to their flourishing because it was enacted by a large legislature rather than imposed by a single bully. The effect on the person being forced is the same.',
      'Cooperation itself is what scales. Language scaled from small groups to global communication. Markets scaled from village barter to worldwide commerce. Standards of behavior scaled from tribal custom to international norms. Every one of these was a technology of voluntary coordination that people said couldn\'t work beyond a small group — until it did.',
      'The real scaling problem runs in the other direction. Force scales <em>badly</em>. The larger the group, the less the enforcers know about the people they\'re coercing, the less feedback they receive, and the more damage they do per mistake. A parent who forces a child to eat vegetables may be wrong, but the harm is contained. A government forcing a nutrition policy on millions produces cascading unintended consequences — because the people making the rules are strangers to the people living under them.'
    ],
    concession: 'Voluntary cooperation at scale requires something coercion doesn\'t: trust between strangers. Building that trust is genuinely harder than passing a law. The philosophy doesn\'t claim the transition is simple. It claims that the alternative — forcing strangers to comply with rules they didn\'t choose — produces the very mistrust that makes cooperation seem impossible. Trust is built by cooperating. It is eroded by coercing.',
    question: 'You wouldn\'t use force on someone you know because you understand what it does to them. What makes you confident it does something different to someone you don\'t know?'
  },

  'too-urgent': {
    title: '"People are suffering right now. They can\'t wait for voluntary action."',
    subtitle: 'Urgency demands guaranteed response, not hopeful cooperation.',
    steelman: 'A child is hungry right now. A person is dying of a treatable disease right now. A family lost their home right now. You can philosophize about voluntary cooperation, but these people can\'t wait for someone to be persuaded to help. Compulsory systems exist because urgent suffering demands guaranteed, immediate response. Leaving it to voluntary action means accepting that some people will simply not be helped.',
    response: [
      'This objection carries real moral weight, and the philosophy takes it seriously. But notice the assumption underneath it: that the only way to guarantee help is to force people to provide it. This assumes that human beings, left free, will not respond to suffering. That assumption is worth testing.',
      'When disaster strikes — hurricanes, earthquakes, floods — voluntary response is not slow. It is often faster and more effective than government mobilization. After Hurricane Katrina, volunteer boat rescuers reached stranded families while FEMA was still processing paperwork. After earthquakes, neighbors pull each other from rubble before emergency services arrive. The impulse to help is not something governments created. It is something human beings do.',
      'Now apply the flourishing framework you just worked through. When help is compelled — extracted from some to be given to others through force — what happens to the people on both ends? The person taxed loses autonomy over their resources. The person helped receives aid delivered by a system that has no relationship with them and no incentive to care about their dignity. Contrast this with voluntary help: a community that <em>chooses</em> to support its members creates connection, preserves dignity, and strengthens the social bonds that prevent future crises. Compulsory systems address the symptom. Voluntary systems address the symptom <em>and</em> build the conditions for flourishing.',
      'There is a deeper cost most people don\'t see. When government assumes responsibility for the vulnerable, communities atrophy. Neighbors stop knowing each other. Mutual aid networks dissolve. The very capacity for voluntary response weakens. Then, when the compulsory system fails — as it inevitably does for some — there is nothing left to catch the person who falls.'
    ],
    concession: 'This is where the philosophy must be most honest. During any transition from compulsory to voluntary systems, there is a real risk that some people who currently receive help would experience disruption. The philosophy cannot promise zero casualties. What it can say is this: compulsory systems produce their own suffering — dependency, loss of dignity, bureaucratic indifference, the erosion of community bonds. A system that guarantees a floor may also enforce a ceiling. The question is not whether voluntary systems are perfect. It\'s whether they produce better trajectories for human flourishing than systems built on force.',
    question: 'If you saw a neighbor in crisis, would you help — or would you wait for a government program? If you would help, why do you assume other people wouldn\'t?'
  },

  'force-built-this': {
    title: '"Force built the stability that made your flourishing possible."',
    subtitle: 'You\'re flourishing because of government, not in spite of it.',
    steelman: 'The best period of your life didn\'t happen in a vacuum. It happened inside a society with enforceable laws, public infrastructure, courts, police, and institutions — all funded and maintained through compulsory taxation. The safety, autonomy, and opportunity you identified weren\'t gifts of nature. They were products of a system built on democratic force. You\'re flourishing because of coercive institutions, not in spite of them.',
    response: [
      'This is a serious argument, and it deserves a careful answer. The philosophy does not claim that every outcome produced by government is bad. It claims that the <em>method</em> of force systematically undermines the conditions for flourishing — even when individual outcomes appear positive.',
      'Consider the flourishing conditions you identified: safety, autonomy, connection, competence, purpose, opportunity. Now ask: did coercive institutions <em>create</em> these, or did they emerge in spite of coercion? Safety exists in your neighborhood primarily because your neighbors choose not to harm each other — not because police are on every corner. Your autonomy exists because you\'ve carved out a life within a system that limits your autonomy in dozens of ways you\'ve learned to navigate around. The stability you experience comes largely from the voluntary cooperation of millions of people — showing up to work, honoring agreements, treating strangers with basic decency — with government enforcement filling gaps where voluntary norms have broken down.',
      'The Guide makes a distinction worth sitting with: the trust that makes cooperation possible is built by voluntary behavior, not by enforcement. A neighborhood where people don\'t steal because they respect each other is fundamentally different from one where people don\'t steal because they fear punishment. The first produces genuine trust. The second produces compliance that evaporates the moment enforcement weakens.',
      'There is also a survivorship bias in this argument. You see the stability that compulsory systems produced. You don\'t see the flourishing they prevented — the businesses never started because of regulatory barriers, the communities never formed because zoning laws blocked them, the mutual aid networks that dissolved because government programs replaced them, the innovations never attempted because the cost of compliance was too high. The visible benefits of force are easy to credit. The invisible costs are easy to ignore.'
    ],
    concession: 'The philosophy acknowledges that some compulsory institutions have produced outcomes that voluntary systems haven\'t yet replicated at the same scale. The claim is not that everything government does could have been done better voluntarily yesterday. The claim is that the direction matters: every expansion of voluntary cooperation has historically produced more flourishing than the coercive system it replaced. And every expansion of coercion has produced diminishing returns and increasing unintended harm.',
    question: 'Think about your best period again. How much of what made it good was provided by the government — and how much was built by you and the people around you, through voluntary effort, voluntary relationships, and voluntary commitment?'
  },

  'power-vacuum': {
    title: '"Without enforcement, the powerful will exploit the weak."',
    subtitle: 'Remove government force and worse force fills the vacuum.',
    steelman: 'History is clear: when centralized authority weakens, the powerful fill the vacuum. Warlords, monopolists, slaveholders, feudal lords. Government force isn\'t perfect, but it\'s the best tool humanity has developed for protecting ordinary people from predatory power. Remove it, and the vulnerable suffer most. Your philosophy sounds like freedom for the strong and abandonment of the weak.',
    response: [
      'This objection assumes that government force and private exploitation are the only two options — that without the first, you inevitably get the second. But look at the flourishing framework. The conditions you identified — safety, autonomy, connection — are damaged by <em>both</em> government coercion and private exploitation. The question isn\'t which form of force to accept. It\'s whether there are ways to protect the vulnerable that don\'t require creating an institution with a monopoly on force.',
      'Consider the pattern: every institution created to protect the vulnerable eventually becomes a tool of the powerful. Regulatory agencies are captured by the industries they regulate. Tax systems are shaped by those who can afford lobbyists. Zoning boards serve property developers. Military power is deployed for commercial interests. The institution you\'re relying on to protect the weak is the institution the strong have the greatest incentive and ability to control.',
      'Now consider what <em>actually</em> protects the vulnerable in your own life. When someone in your community is in trouble, what helps them? Government programs, sometimes. But more often: neighbors, friends, family, religious communities, mutual aid networks, charitable organizations. These are voluntary institutions built on trust and connection — and they serve the vulnerable precisely because no one is forced to participate. The people who show up are the people who care. The help they provide preserves dignity because it comes from genuine concern, not bureaucratic obligation.',
      'The philosophy\'s claim is not that the vulnerable don\'t need protection. It\'s that concentrated coercive power is the wrong tool for providing it — because the same concentration of power that can protect can also exploit, and historically does. The alternative is distributed, voluntary, trust-based protection: communities that take care of their own because they\'ve chosen to. This requires stronger social bonds, not weaker ones. More cooperation, not less. But it doesn\'t require anyone to hold a monopoly on force.'
    ],
    concession: 'This is the hardest question the philosophy faces. In the immediate absence of enforcement, some people with power would exploit others. The philosophy doesn\'t deny this. It argues that the solution — concentrating coercive power in one institution and hoping the right people control it — has a worse track record than its defenders acknowledge. But the philosophy must also be honest that voluntary protection requires strong communities, high social trust, and robust mutual aid systems. Building those takes time. During the transition, some people would be more vulnerable than they are today. That cost is real, and any honest philosophy must name it.',
    question: 'The institution you trust to protect the vulnerable has the power to imprison, seize property, and deploy armed agents. Who protects the vulnerable from <em>it</em>?'
  }
}
