-- Legacy baseline: the schema as the original Vue app created it.
--
-- 0001 onward evolve an existing database with ALTER TABLE, because they were
-- written against production, which already had these three tables. That made
-- the migration set unreplayable: a fresh database could not be built from it,
-- and neither could a test environment or a restored backup.
--
-- This reconstructs the original shape so the set runs from empty. Everything
-- is `if not exists`, so it is a no-op against production, where these tables
-- have existed since March 2026.
--
-- Column types match production exactly — in particular `id` is bigint, not
-- uuid, which is what experience_responses.journey_id has to match.

create table if not exists public.journeys (
  id                           bigint generated by default as identity primary key,
  visitor_id                   uuid not null unique,

  -- Progress, as the current app writes it.
  completions                  jsonb       default '{}'::jsonb,
  last_experience              text,
  furthest_tier                text,
  total_experiences            integer     default 0,
  first_visit                  timestamptz,
  last_visit                   timestamptz,
  created_at                   timestamptz default now(),
  updated_at                   timestamptz default now(),

  -- Per-experience columns from the original build. Still written by the
  -- legacy Cloudflare deployment, so they are preserved rather than dropped.
  exp01_completed              boolean     default false,
  exp01_completed_at           timestamptz,
  exp01_methods                text[],
  exp01_would_force            text,
  exp01_why_not                text[],
  exp02_objection              text,
  exp02_completed              boolean     default false,
  exp02_completed_at           timestamptz,
  exp02_verdict                text,
  exp02_concession_credibility text,
  exp03_completed              boolean     default false,
  exp03_completed_at           timestamptz
);

create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  visitor_id  uuid,
  event_name  text not null,
  properties  jsonb       default '{}'::jsonb,
  created_at  timestamptz default now()
);

create table if not exists public.newsletter_subscribers (
  id             bigint generated by default as identity primary key,
  email          text not null unique,
  source         text,
  visitor_id     uuid,
  subscribed_at  timestamptz default now(),
  confirmed      boolean     default false
);

-- RLS was on from the start. The permissive legacy policies are deliberately
-- not recreated here: 0003 drops the dangerous one and installs the real
-- rules, and a fresh database should never briefly have the hole.
alter table public.journeys enable row level security;
alter table public.events enable row level security;
alter table public.newsletter_subscribers enable row level security;
